config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#start"
  # Defines the root path route ("/")
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:index]
    end
  end

  namespace :api do
    namespace :v1 do
      get "comments/index"
      get "comments/create"
      get "posts/index"
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: %i[index create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    can :create, [Post, Comment]

    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Post, author_id: user.id
      can :destroy, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_comments_counters
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_likes_counters
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id', required: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def update_posts_counters
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, stretches: 13
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      skip_before_action :verify_authenticity_token
      skip_before_action :authenticate_user!
      respond_to :json

      def index
        user = User.find(params[:user_id])
        post = user.posts.find(params[:post_id])
        comments = post.comments

        respond_with comments
      end

      def create
        user = User.find(params[:user_id])
        post = user.posts.find(params[:post_id])
        comment = post.comments.build(comment_params)
        comment.user = user

        if comment.save
          render json: comment, status: :created
        else
          render json: { errors: comment.errors.full_messages }, status: :unprocessable_entity
        end
      end

      private

      def comment_params
        params.require(:comment).permit(:text)
      end
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      skip_before_action :verify_authenticity_token
      skip_before_action :authenticate_user!
      respond_to :json
      def index
        user = User.find(params[:user_id])
        posts = user.posts
        respond_with posts
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = %i[name photo bio]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  # load_and_authorize_resource

  def create
    post = Post.find(params[:post_id])
    message = comment_params
    @comment = Comment.create(user: current_user, post:, text: message[:text])
    @comment.save
    @comment.update_comments_counters
    redirect_to user_post_url(current_user, post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    @post.comments_counter -= 1
    @post.save
    @comment.destroy
    redirect_to user_post_path(@post.author, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.includes(:comments, :likes).find_by(id: params[:post_id])
    @likes = Like.where(user: current_user, post: @post).first
    unless @likes
      @like = Like.create(user: current_user, post: @post)
      @like.save
      @like.update_likes_counters
    end
    redirect_to user_post_path(@post.author, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @user = User.includes(:posts, :comments, :likes).find_by(id: params[:user_id])
    @posts = @user.posts.includes(:comments, :likes)
  end

  def show
    @user = User.includes(:posts, :comments, :likes).find_by(id: params[:user_id])
    @post = @user.posts.find(params[:id])
    @comment = Comment.new
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    post = post_params
    @post = Post.create(author: current_user, title: post[:title], text: post[:text])
    @post.save
    @post.update_posts_counters
    redirect_to user_post_path(current_user, @post)
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @post.destroy
    @user.posts_counter -= 1
    @user.save
    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def start
    p current_user
    redirect_to users_path
  end

  def index
    @users = User.includes(:posts, :comments, :likes).all
  end

  def show
    @user = User.includes(:posts, :comments, :likes).find_by(id: params[:id])
    @posts = if @user
               @user.recent_posts
             else
               []
             end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Applications</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if user_signed_in? %>
    <div class="container">
    <%= form_tag "/users/sign_out", method: :delete do %>
      <div class="horizon">
      <%= submit_tag("Sign Out", class: "btn-signout") %>
      </div>
    <% end %>
    <div>
    <% end %>
  </body>
</html>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("user") %>
<div class="container">
<ul class="unorder-list">
    <li class="list-items list-profile">
    <%= image_tag("profile/#{@user.photo}", class: "profile_img") %>
    </li>
    <li class="list-items list-desc">
    <p class="name-title"><%= link_to @user.name, @user %></p>
     <p class="quantity">Number of post
     <%= @user.posts_counter %>
     </p>
    </li>
</ul>
<% @posts.each do |post| %>
    <ul class="unorder-list">
    <li class="list-items list-content">
    <h3 class="post-title"><%= link_to post.title, user_post_path(@user, post) %></h3>
    <p class="name-title"><%= post.text %></p>
    <p class="quantity">
     comments:<span><%= post.comments_counter %></span>
     Likes:<span><%= post.likes_counter %></span>
     </p>
    </li>
    </ul>
    <% if (post.comments.first) %>
    <ul class="unorder-list">
    <li class="list-items list-content">
    <p class="name-title">
    <%= post.comments.first.user.name %> : 
    <span><%= post.comments.first.text %><span> </p>
      </li>
</ul>
<% end %>
<br>
<% end %>
<div class="expand-link">
      <button type="button" class="see-more">
      <%= link_to "Pagination", user_posts_path(@user) %>
      </button>
      </div>
</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag("post") %>
<div class="container">
<div class="form-container">
<div class="form-header">Add New Post</span><small> by Osman </small></div>
<%= form_with model: [@user, @post] do |form| %>
    <div class="form-label"><%= form.label :title %></div>
    <div class="form-input"><%= form.text_field :title %></div>
    <div class="form-label"><%= form.label :Description %></div>
    <div class="form-input"><%= form.text_area :text %></div>
    <div><%= form.submit "Post", class: "add-comment" %></div>
  <% end %>
</div>  
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag("user") %>
<div class="container">
    <ul class="unorder-list">
    <li class="list-items list-content">
    <div class="post-details">
    <p class="post-title"> 
    <strong><%= @post.title %></strong> by
    <strong><%= @user.name %></strong></p>
    <p class="quantity">
     comments:<span><%= @post.comments_counter %></span>
     Likes:<span><%= @post.likes_counter %></span>
     </p>
    </div>
    <p class="post-content"><%= @post.text %></p>
    <% if can? :destroy, @post %>
    <%= form_tag user_post_path(@post.author, @post), method: :delete do %>
      <div class="form-destroy">
      <%= submit_tag("Delete", class: "btn-destroy") %>
      </div>
    <% end %>
    <% end %>
    </li>
    </ul>
    <% if (@post.comments.length > 0) %>
     <% @post.comments.each do |comment| %>
      <ul class="unorder-list">
    <li class="list-items list-content list-comments">
      <%= form_tag user_post_comment_path(@post.author, @post, comment), method: :delete do %>
        <div>
        <span><%= comment.user.name %> </span>:
        <span><%= comment.text %> </span>
        </div>
      <% if can? :destroy, comment %>
        <div class="comment-delete">
        <%= submit_tag("Delete", class: "btn-destroy") %>
        </div>
      <% end %>
      <% end %>
      </li>
   </ul>
  <% end %>
 <% end %>
<%= form_with model: [@user, @post, @comment] do |form| %>
  <div class="post_comment">
       <div class="input-comment">
       <%= form.text_field :text %>
       </div>
      <div class="submit-comment">
       <%= form.submit "Comment" %>
       <%= link_to "Like", user_post_likes_path(@user, @post) %>
       </div>
       </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag("user") %>
<div class="container">
<h1>Users List</h1>
  <% @users.each do |user| %>
<ul class="unorder-list">
    <li class="list-items list-profile">
    <%= image_tag("profile/#{user.photo}", class: "profile_img") %>
    </li>
    <li class="list-items list-desc">
    <p class="name-title"><%= link_to user.name, user %></p>
     <p class="quantity">Number of post
     <%= user.posts_counter %>
     </p>
    </li>
</ul>
  <% end %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag("user") %>
<div class="container">
<ul class="unorder-list">
    <li class="list-items list-profile">
    <%= image_tag("profile/avator.png", class: "profile_img") %>
    </li>
    <li class="list-items list-desc">
    <p class="name-title"><%= link_to @user.name, @user %></p>
     <p class="quantity">Number of post
     <%= @user.posts_counter %>
     </p>
    </li>
</ul>
<ul class="unorder-list">
    <li class="list-items list-content">
    <h3>Bio</h3>
    <p class="name-title"><%= @user.bio %></p>
    </li>
</ul>
<% @posts.each do |post| %>
    <ul class="unorder-list">
    <li class="list-items list-content">
    <h3 class="post-title"><%= link_to post.title, user_post_path(@user, post) %></h3>
    <p class="name-title"><%= post.text %></p>
    <p class="quantity">
     comments:<%= post.comments_counter %>
     Likes:<%= post.likes_counter %>
     </p>
    </li>
    </ul>
      <% end %>
      <div class="expand-link">
      <button type="button", class="see-more"                   %>
      <%= link_to "See all Posts", user_posts_path(@user) %>
      </button>
      </div>
</div>